version: "3.8"

services:
  server:
    build: ./server
    container_name: poll_server
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://polling_app:polling_pass@db:5432/polling_app
      JWT_SECRET: a27cb5ba253b545c8662ceec955cdca2873f467bc3882adf84d7f2298462c61f
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "npx prisma migrate deploy && 
             npx prisma db seed && 
             npm run start"

  client:
    build: ./client
    container_name: poll_client
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:4000/graphql
      NODE_ENV: production
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16-alpine
    container_name: polling_db
    restart: always
    environment:
      POSTGRES_USER: polling_app
      POSTGRES_PASSWORD: polling_pass
      POSTGRES_DB: polling_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U polling_app -d polling_app"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: